### ISSUE TITLE
Cross platform client 

### ISSUE THREAD

**Issue by LexiconCode** [dwks/silvius#10]
Linux is great but Silvius needs a cross-platform client and preferably architecture agnostic. We need to make this as easy as possible to experiment and not just for programmers. Easy experimentation leads to adoption, then innovation. Therefore we might start evaluating implementation of libraries that would work cross-platform most likely but not necessarily python. 

I would say we need to discuss how the project is currently structure and therefore our approach about planning and implementation. 

Available Hardware for testing purposes.
Microsoft 10 64-bit(Linux Ubuntu system installed), Linux (any flavor) amd64, oDroid c2(64bit ARMv8), Raspberry Pi 3(64bit ARMv7), Pine A64(ARMv8), oDroid xu4(ARMv7),
Emulated Mac OS (VirtualBox)

https://github.com/dwks/silvius/issues/8 could be merged

**Comment by dwks** [comment]
OK, this seems like a good idea. I don't think any changes will be needed to support other architectures like aarch64. However, non-Linux platforms won't be able to use xdotool, which is hard-coded right now in execute.py and in some translation tables in parse.py (e.g. turning 'double' into 'quotedbl'). I can refactor this into a platform-specific source file.

On Mac, we can use an AppleScript backend. On Windows, I'm not sure what the appropriate mechanism would be, but we can look at how dragonfly does things.

**Comment by dwks** [comment]
Implemented in #26 by @jvanloov.
