### ISSUE TITLE
Chaining modifiers and using modifier followed by digit

### ISSUE THREAD

**Issue by crypdick** [dwks/silvius#11]
I use the i3 windows manager, and I use the Super key to navigate windows. I added support for the super modifier (here: https://github.com/crypdick/silvius/blob/master/grammar/parse.py#L233) and it works for Super+Letter combinations. However, this does not work with Super+digit or chained modifiers (e.g. Super+Shift+q).

**Comment by dwks** [comment]
Have you tried saying "control number three?" That's the way you should be
able to speak a number in the grammar. If that, or combinations, aren't
working then silvius is probably generating key release events too early.
You can check the exact string passed to the xdotool external command to
see if it looks right.

EDIT: I verified the chaining "+" bug and chained modifiers bug, working on a fix.

**Comment by dwks** [comment]
I fixed both problems in c10308b, please test.

**Comment by crypdick** [comment]
It works! The only  think missing is the Shift key. Do you think I should implement it as another modifier?

**Comment by dwks** [comment]
Yeah, good idea. There is "sky", but only for letters. If you implement shift & super I will merge it to master.
