### ISSUE TITLE
Saying a number in a sentence throws an error

### ISSUE THREAD

**Issue by crypdick** [dwks/silvius#12]
If I try to say "phrase something something something one" I get this error:

```
[phrase, ANY, ANY, ANY, one, END]
Error: Unexpected token `one' (word number 5)
```

Works with every number I tried:

```
> phrase five
[phrase, five, END]
Error: Unexpected token `five' (word number 2)

```

**Comment by dwks** [comment]
Fixed in 4d57276. The root problem is that the lexer always handles command words, even out of context. So any command words which do not actually begin a command need to be slurped into the "phrase/sentence" code. There may be other examples like this.
