### ISSUE TITLE
Using two for a repeat is broken

### ISSUE THREAD

**Issue by crypdick** [dwks/silvius#20]
For example, scratch two:

```
> scratch to
[scratch, to, END]
Error: Unexpected token `to' (word number 2)
```

```
> down to
[down, to, END]
Error: Unexpected token `to' (word number 2)
```

**Comment by crypdick** [comment]
Update: `scratch four" is also broken.

**Comment by dwks** [comment]
I am currently working on a smarter language model which should not suffer from this issue. As a temporary fix, you can add "to" and "for" as aliases of "two"/"four" in the grammar.

**Comment by dwks** [comment]
I just implement this in d810801, cheers.
