### ISSUE TITLE
How to scratch more than 9 characters?

### ISSUE THREAD

**Issue by crypdick** [dwks/silvius#21]
I can say `scratch <any digit>` to repeatly hit backspace (with the exception of number 2, see #20). However, I can't say `scratch three zero` or `scratch number three number zero` to repeat 30 times.

**Comment by dwks** [comment]
Implemented in 8806dca, up to 999 billion. Don't spell out the digits but rather speak numbers as in english e.g. "nine hundred ninety nine thousand".
