### ISSUE TITLE
removing a stream sound bites

### ISSUE THREAD

**Issue by aliudinwijaya** [dwks/silvius#3]
sorry, if pieces of the result of streaming audio mic conducted by mic.py, layout frame her pieces where?

Best regards
thanks

**Comment by dwks** [comment]
Sorry, are you asking how to remove extra unwanted recognitions from the stream (where you didn't actually say anything), or how to actually use the output of mic.py? In the second case, you would pipe the results through grammar/main.py. We have a new run.sh script which will make it easier, just try "./run.sh --execute".

**Comment by aliudinwijaya** [comment]
if you want to release the results audio?

best regards
thanks

**Comment by dwks** [comment]
I believe the recorded audio is by default stored on the server side in the kaldi-gstreamer-server/tmp/ directory. I'm not sure of the exact format. If you want to record the audio as it is sent, packet by packet, to create a wav file, you could do that on the client side or the server side.
