### ISSUE TITLE
No silvius-backend link

### ISSUE THREAD

**Issue by excalamus** [dwks/silvius#33]
There is mention of a server-client architecture, yet no active reference to the server component.

voxhub.io appears to be offline.

Here is an archived link: [https://web.archive.org/web/20190425050145/http://voxhub.io/silvius](https://web.archive.org/web/20190425050145/http://voxhub.io/silvius)

From there I found the server component: [https://github.com/dwks/silvius-backend](https://github.com/dwks/silvius-backend)

**Comment by dwks** [comment]
The VPS was down (fixed now). This isn't the first time it's happened, I'm considering moving to a new provider. For now, I'm running two VPS's

http://voxhub.io/
http://mirror.voxhub.io/

**Comment by dwks** [comment]
Added a link to the server repo in case the website ever goes down again in 4952f76e0cbbe7f9454264a31ceea9b9706bdf35.
