### ISSUE TITLE
Any support for mac?

### ISSUE THREAD

**Issue by dylan-chong** [dwks/silvius#8]

**Comment by dwks** [comment]
Not yet. It would have to be implementing using AppleScript. You'd replace the xdotool commands in [execute.py](https://github.com/dwks/silvius/blob/master/grammar/execute.py) with AppleScript commands built up as in this OS X implementation for Aenea:

https://github.com/dictation-toolbox/aenea/blob/master/server/osx/server_osx.py

It probably wouldn't take long to do this, and although I don't have access to a Mac right now, let me know if you want help.

**Comment by dwks** [comment]
@jvanloov added mac support using the cliclick tool in #26!
