### ISSUE TITLE
Ambient sounds recognized as input

### ISSUE THREAD

**Issue by Yorgg** [dwks/silvius#9]
Ambient noise (not human speech, but typing, clicking, rustling etc..) is being falsely recognized as words.   
This happens every few seconds and in a silent bedroom.

I tried two mics with same results:  the built in imac microphone, and a Rode XLR mic connected to external audio interface.  I also tried lowering the line input level.   

Is there any way to reduce/stop this?

(on Mac, Sierra)

thanks!

**Comment by dwks** [comment]
A previous user jasonleekennedy implemented "audio gating", where sound
below a certain threshold is filtered out. You have to find an appropriate
value for your microphone and it may reduce accuracy slightly, but you
should give it a try (see -G option in run.sh for example). Ultimately,
this is a by-product of my tweaking the grammar probabilities; I should
perhaps also have adjusted the probability of recognizing silence. P.S. Can
you say which microphone you're using and which gate value was appropriate
for it?

**Comment by Yorgg** [comment]
Thanks, I didn't notice the -G option at that time.  ^^
